import { Prisma, PrismaClient } from "@prisma/client";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import axios from "axios";
import { createRouter } from "../create-router";
import { Fields } from "../../types";

const LOGTAIL_API_TOKEN = process.env.NEXT_PUBLIC_LOGTAIL_API_TOKEN;

const prisma = new PrismaClient();
const defaultMembersSelect = Prisma.validator<Prisma.MemberSelect>()({
  id: true,
  createdAt: true,
  updatedAt: true,
  date: true,
  branchName: true,
  memberId: true,
  firstName: true,
  lastName: true,
  dob: true,
  idPass: true,
  kraPin: true,
  phoneNumber: true,
  gender: true,
  age: true,
  religion: true,
  maritalStatus: true,
  spouseName: true,
  spouseNumber: true,
  postalAddress: true,
  postalCode: true,
  cityTown: true,
  residentialAddress: true,
  emailAddress: true,
  rentedOwned: true,
  landCareAgent: true,
  occupationEmployer: true,
  employerNumber: true,
  businessLocation: true,
  businessAge: true,
  refereeName: true,
  refereeNumber: true,
  communityPosition: true,
  mpesaCode: true,
  membershipAmount: true,
  nameKin: true,
  relationship: true,
  residentialAddressKin: true,
  postalAddressKin: true,
  postalCodeKin: true,
  cityTownKin: true,
  numberKin: true,
  maintained: true,
  group: true,
})

export const membersRouter = createRouter()
  .query("members", {
    resolve: async () => {
      return await prisma.member.findMany();
    },
  })
  .mutation("register", {
    input: z.object({
      date: z.string(),
      branchName: z.string(),
      memberId: z.string(),
      firstName: z.string(),
      lastName: z.string(),
      dob: z.string(),
      idPass: z.string(),
      kraPin: z.string(),
      phoneNumber: z.string(),
      gender: z.string(),
      age: z.string(),
      religion: z.string(),
      maritalStatus: z.string(),
      spouseName: z.string(),
      spouseNumber: z.string(),
      postalAddress: z.string(),
      postalCode: z.string(),
      cityTown: z.string(),
      residentialAddress: z.string(),
      emailAddress: z.string(),
      rentedOwned: z.string(),
      landCareAgent: z.string(),
      occupationEmployer: z.string(),
      employerNumber: z.string(),
      businessLocation: z.string(),
      businessAge: z.string(),
      refereeName: z.string(),
      refereeNumber: z.string(),
      communityPosition: z.string(),
      mpesaCode: z.string(),
      membershipAmount: z.string(),
      nameKin: z.string(),
      relationship: z.string(),
      residentialAddressKin: z.string(),
      postalAddressKin: z.string(),
      postalCodeKin: z.string(),
      cityTownKin: z.string(),
      numberKin: z.string(),
      group: z.boolean(),
      maintained: z.boolean(),
    }),
    resolve: async ({ input }) => {
      return await prisma.member.create({
        data: {
          date: input.date,
          branchName: input.branchName,
          memberId: input.memberId,
          firstName: input.firstName,
          lastName: input.lastName,
          dob: input.dob,
          idPass: input.idPass,
          kraPin: input.kraPin,
          phoneNumber: input.phoneNumber,
          gender: input.gender,
          age: input.age,
          religion: input.religion,
          maritalStatus: input.maritalStatus,
          spouseName: input.spouseName,
          spouseNumber: input.spouseNumber,
          postalAddress: input.postalAddress,
          postalCode: input.postalCode,
          cityTown: input.cityTown,
          residentialAddress: input.residentialAddress,
          emailAddress: input.emailAddress,
          rentedOwned: input.rentedOwned,
          landCareAgent: input.landCareAgent,
          occupationEmployer: input.occupationEmployer,
          employerNumber: input.employerNumber,
          businessLocation: input.businessLocation,
          businessAge: input.businessAge,
          refereeName: input.refereeName,
          refereeNumber: input.refereeNumber,
          communityPosition: input.communityPosition,
          mpesaCode: input.mpesaCode,
          membershipAmount: input.membershipAmount,
          nameKin: input.nameKin,
          relationship: input.relationship,
          residentialAddressKin: input.residentialAddressKin,
          postalAddressKin: input.postalAddressKin,
          postalCodeKin: input.postalCodeKin,
          cityTownKin: input.cityTownKin,
          numberKin: input.numberKin,
          group: input.group,
          maintained: input.maintained,
          ratings: 0,
        },
      });
    },
  });
